docs(developer): fixed AWS IAM Authenticator install command
Using the original command yielded the following compilation error:

```bash
development/src/github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator/root.go:69:18: cannot use config.DefaultFeatureGates (type map["sigs.k8s.io/aws-iam-authenticator/vendor/k8s.io/component-base/featuregate".Feature]"sigs.k8s.io/aws-iam-authenticator/vendor/k8s.io/component-base/featuregate".FeatureSpec) as type map["github.com/kubernetes-sigs/aws-iam-authenticator/vendor/k8s.io/component-base/featuregate".Feature]"github.com/kubernetes-sigs/aws-iam-authenticator/vendor/k8s.io/component-base/featuregate".FeatureSpec in argument to featureGates.Add
```

and failed to install the required binary, probably due to some
broken dependency state on the current main branch.

After checking the repository the package itself advertises the
usage of a different installation command:

```bash
go get -u -v sigs.k8s.io/aws-iam-authenticator/cmd/aws-iam-authenticator
```

which worked flawlessly, so I'm replacing the original command in
the documentation with the new one.

Also keeping the verbose -v flag, because the installation takes a
noticable amount of time with no non-verbose output (around 40s).